from utils.config_loader import Config
from jinja2 import Template
import smtplib
from email.message import EmailMessage
from datetime import datetime
import os


def send_meeting_notification(
    recipient_email: str,
    notification_type: str,
    meeting_details: dict,
    ics_attachment: str = None
) -> dict:
    """
    Sends email notifications for meeting events.

    Parameters:
    -----------
    recipient_email : str
        Email address of the recipient

    notification_type : str
        One of: "invite", "update", "cancel"

    meeting_details : dict
        {
            "title": "Team Sync",
            "start": "2025-01-27T15:00:00",
            "end": "2025-01-27T16:00:00",
            "link": "https://meet.google.com/abc-defg-hij",
            "organizer": "Aniket Barun"
        }

    ics_attachment : str (optional)
        Path to .ics file generated by utils/ics_generator.py

    Returns:
    --------
    dict:
        Success:
        {
            "success": True,
            "recipient": "...",
            "notification_type": "...",
            "sent_at": "2025-01-27T10:30:00"
        }

        Failure:
        {
            "success": False,
            "error": "SMTP authentication failed"
        }
    """

    try:
        # 1) Load config (sender credentials)
        config = Config()
        sender_email = config.get("SENDER_EMAIL")
        sender_password = config.get("SENDER_PASSWORD")

        if not sender_email or not sender_password:
            return {
                "success": False,
                "error": "Missing SENDER_EMAIL or SENDER_PASSWORD"
            }

        # 2) Load template based on notification_type
        if notification_type == "invite":
            template_path = "templates/email_invite.html"
            subject = f"Meeting Invitation: {meeting_details.get('title', 'Meeting')}"
        elif notification_type == "update":
            template_path = "templates/email_update.html"
            subject = f"Meeting Updated: {meeting_details.get('title', 'Meeting')}"
        elif notification_type == "cancel":
            template_path = "templates/email_cancel.html"
            subject = f"Meeting Cancelled: {meeting_details.get('title', 'Meeting')}"
        else:
            return {
                "success": False,
                "error": "Invalid notification_type (must be invite/update/cancel)"
            }

        if not os.path.exists(template_path):
            return {
                "success": False,
                "error": f"Template file not found: {template_path}"
            }

        # 3) Render template with meeting_details using Jinja2
        with open(template_path, "r", encoding="utf-8") as f:
            html_template = f.read()

        template = Template(html_template)

        # IMPORTANT:
        # Your invite template uses variables like {{ title }}, {{ time_str }}, {{ location }}, {{ agenda }}
        # But meeting_details in contract contains title/start/end/link/organizer
        #
        # So we build a render dict that supports both.
        render_data = meeting_details.copy()

        # Provide extra computed fields for existing template compatibility
        if "time_str" not in render_data:
            start = meeting_details.get("start", "")
            end = meeting_details.get("end", "")
            render_data["time_str"] = f"{start} to {end}"

        if "location" not in render_data:
            render_data["location"] = meeting_details.get("link", "N/A")

        if "agenda" not in render_data:
            render_data["agenda"] = "N/A"

        html_body = template.render(**render_data)

        # 4) Create EmailMessage object
        msg = EmailMessage()
        msg["From"] = sender_email
        msg["To"] = recipient_email
        msg["Subject"] = subject

        msg.set_content("Meeting notification (HTML supported email recommended).")
        msg.add_alternative(html_body, subtype="html")

        # 5) Attach .ics file if provided
        if ics_attachment:
            if not os.path.exists(ics_attachment):
                return {
                    "success": False,
                    "error": f"ICS file not found: {ics_attachment}"
                }

            with open(ics_attachment, "rb") as f:
                ics_data = f.read()

            msg.add_attachment(
                ics_data,
                maintype="text",
                subtype="calendar",
                filename=os.path.basename(ics_attachment)
            )

        # 6) Send email via Gmail SMTP
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender_email, sender_password)
            server.send_message(msg)

        # 7) Return success dict
        return {
            "success": True,
            "recipient": recipient_email,
            "notification_type": notification_type,
            "sent_at": datetime.utcnow().isoformat()
        }

    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "error": "SMTP authentication failed"
        }

    except smtplib.SMTPException as e:
        return {
            "success": False,
            "error": f"SMTP error: {str(e)}"
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }
