"""
smart_agenda_engine.py
----------------------
Generates personalized daily meeting briefings.

Feature 8: Preparation suggestions are now generated by the LLM (Gemini)
instead of hardcoded heuristic strings.  Heuristics are kept as a fallback
if the LLM call fails.
"""

import json
import re
from datetime import datetime

from src.services.meeting_fetcher import fetch_meetings
from src.utils.config_loader import get_llm_client


def _llm_suggestions(title: str, start: datetime, duration_minutes: int, attendees: list) -> list:
    """Call Gemini to generate 2-3 specific preparation tips for a meeting."""
    try:
        llm = get_llm_client()
        attendee_str = ", ".join(
            a.get("name") or a.get("email", "") for a in attendees if a
        ) or "None listed"

        system_prompt = (
            "You are a meeting preparation assistant for university faculty. "
            "Generate 2-3 concise, specific preparation suggestions for an upcoming meeting. "
            "Be practical and tailored to the meeting title and attendees."
        )
        user_prompt = (
            f"Meeting : {title}\n"
            f"Time    : {start.strftime('%I:%M %p')} ({duration_minutes} minutes)\n"
            f"Attendees: {attendee_str}\n\n"
            "Return a JSON array of 2-3 short suggestion strings only. No explanation."
        )

        raw = llm.generate(system_prompt=system_prompt, user_prompt=user_prompt)
        cleaned = re.sub(r"^```(json)?\s*|\s*```$", "", raw.strip()).strip()
        suggestions = json.loads(cleaned)
        if isinstance(suggestions, list):
            return [str(s) for s in suggestions]
    except Exception:
        pass

    # Heuristic fallback
    suggestions = []
    if start.hour < 12:
        suggestions.append("Review your notes before the meeting")
    if duration_minutes >= 60:
        suggestions.append("Prepare agenda points in advance")
    if start.hour >= 15:
        suggestions.append("Keep buffer time before this meeting")
    return suggestions


def generate_daily_briefing(user_email: str, date: str) -> dict:
    """
    Generate a personalized daily meeting agenda briefing for a faculty member.

    Parameters
    ----------
    user_email : str  — faculty member's email
    date       : str  — ISO date string (YYYY-MM-DD)
    """

    try:
        day_start = f"{date}T00:00:00Z"
        day_end   = f"{date}T23:59:59Z"

        fetch_result = fetch_meetings(user_email, day_start, day_end)

        if not fetch_result["success"]:
            return fetch_result

        meetings = fetch_result["data"]["meetings"]

        if not meetings:
            return {
                "success": True,
                "data": {
                    "summary":     "You have no meetings scheduled today.",
                    "meetings":    [],
                    "conflicts":   [],
                    "preparation": {},
                },
                "message":    "No meetings for today",
                "error_code": None,
            }

        intervals   = []
        meeting_map = {}

        for meeting in meetings:
            start_raw = meeting["start"]
            end_raw   = meeting["end"]
            if not start_raw or not end_raw:
                continue

            start = datetime.fromisoformat(start_raw.replace("Z", ""))
            end   = datetime.fromisoformat(end_raw.replace("Z", ""))
            intervals.append((start, end))
            meeting_map[(start, end)] = meeting

        intervals.sort(key=lambda x: x[0])

        # Detect overlapping meetings
        conflicts = []
        for i in range(len(intervals) - 1):
            if intervals[i][1] > intervals[i + 1][0]:
                conflicts.append({
                    "first":  meeting_map[intervals[i]].get("title"),
                    "second": meeting_map[intervals[i + 1]].get("title"),
                })

        # LLM-generated preparation suggestions per meeting (Feature 8)
        preparation = {}
        for start, end in intervals:
            meeting      = meeting_map[(start, end)]
            duration_min = (end - start).seconds // 60
            suggestions  = _llm_suggestions(
                title=meeting.get("title", ""),
                start=start,
                duration_minutes=duration_min,
                attendees=meeting.get("attendees", []),
            )
            preparation[meeting.get("id", str(start))] = {
                "title":       meeting.get("title"),
                "suggestions": suggestions,
            }

        summary = f"You have {len(intervals)} meeting(s) today."
        if conflicts:
            summary += f" {len(conflicts)} scheduling conflict(s) detected."

        return {
            "success": True,
            "data": {
                "summary":     summary,
                "meetings":    meetings,
                "conflicts":   conflicts,
                "preparation": preparation,
            },
            "message":    "Daily briefing generated successfully",
            "error_code": None,
        }

    except Exception as e:
        return {
            "success":    False,
            "data":       None,
            "message":    str(e),
            "error_code": "AGENDA_ENGINE_ERROR",
        }
