"""
Idempotent migration v9: Telegram channel parallel to WhatsApp.

  - users.telegram_chat_id   BIGINT  (Telegram chat IDs can exceed int32)
  - users.telegram_username  VARCHAR(64)
  - telegram_pairing_codes   short-lived 6-char codes for /start binding
  - whatsapp_audit.channel   VARCHAR(16) DEFAULT 'whatsapp'   (so the same
                             audit table tracks both channels)

Run AFTER migrate_v8_booking_briefing.py.

    python scripts/migrate_v9_telegram.py
"""

import sys
from pathlib import Path

import psycopg2
from psycopg2 import OperationalError

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.utils.config_loader import Config


MIGRATION_SQL = """
-- ----------------------------------------------------------------------
-- USERS: add Telegram identity columns
-- ----------------------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_chat_id   BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_username  VARCHAR(64);

-- One Telegram account binds to at most one user; nulls allowed (most users
-- haven't connected yet). Partial unique index keeps that invariant cheaply.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_telegram_chat
    ON users(telegram_chat_id) WHERE telegram_chat_id IS NOT NULL;


-- ----------------------------------------------------------------------
-- telegram_pairing_codes
--   Short-lived (5 min) codes generated by /api/v1/me/telegram/pair and
--   consumed when the user DMs the bot `/start <CODE>`. We keep them in
--   Postgres rather than Redis so a backend restart during the demo
--   doesn't blow away an outstanding code mid-pairing.
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telegram_pairing_codes (
    code        VARCHAR(8) PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    org_id      INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at  TIMESTAMP NOT NULL,
    consumed    BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_pairing_user
    ON telegram_pairing_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_pairing_open
    ON telegram_pairing_codes(expires_at)
    WHERE consumed = FALSE;


-- ----------------------------------------------------------------------
-- whatsapp_audit: add a `channel` column so Telegram inbound/outbound
-- turns log to the same table. Default keeps existing rows interpretable.
-- ----------------------------------------------------------------------
ALTER TABLE whatsapp_audit
    ADD COLUMN IF NOT EXISTS channel VARCHAR(16) DEFAULT 'whatsapp';

CREATE INDEX IF NOT EXISTS idx_wa_audit_channel
    ON whatsapp_audit(channel, created_at DESC);
"""


def main() -> None:
    try:
        conn = psycopg2.connect(Config.DATABASE_URL)
    except OperationalError as err:
        print(f"❌ Could not connect to DB: {err}")
        sys.exit(1)

    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(MIGRATION_SQL)
        print("✅ v9 migration applied: users.telegram_*, "
              "telegram_pairing_codes, whatsapp_audit.channel")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
